In [1]:
import numpy as np

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([2,5,3,8,2])

print("\nAddition")
print(arr1 + arr2)
print("\nMultiply")
print(arr1 * arr2)
print("\nDivide")
print(arr1 / arr2)
print("\nPoweroff")
print(arr1 ** arr2)


Addition
[ 3  7  6 12  7]

Multiply
[ 2 10  9 32 10]

Divide
[0.5 0.4 1.  0.5 2.5]

Poweroff
[    1    32    27 65536    25]
