In [5]:

#Part 1 – Implement Basic Data Structures using Numpy, Pandas

#1. List

list = [2,4,10.5,True,"hello world"]
print(list)

#List Operations

#1.Concatenation
print("\n1.Concatenation")
l1 = ["Hello World"]
l2 = [1 , 2, 3]
print(l1 + l2)

#2.Repetation
print("\n2.Repetation")
l3 = ["SR University"]
print(l3*3)

#3.Membership
print("\n3.Membership")
l1 = ["sru","srit","sriit"]
print("sru" in l1)
print("SRU" in l1)

#4.Slicing
#[start:end:step]
print("\n4.Slicing")
list1 = [1,"a","apple",4,2.5,"!"]
print(list1[0:5])
print(list1[2:4])
print(list1[::-1]) #reverse 


[2, 4, 10.5, True, 'hello world']

1.Concatenation
['Hello World', 1, 2, 3]

2.Repetation
['SR University', 'SR University', 'SR University']

3.Membership
True
False

4.Slicing
[1, 'a', 'apple', 4, 2.5]
['apple', 4]
['!', 2.5, 4, 'apple', 'a', 1]


In [6]:
#2. Array
  
r = int(input("Enter number of rows: "))
c = int(input("Enter number of columns: "))
m1 = []

for i in range(r):
    a = []
    for i in range(c):
        a.append(int(input("Enter element: ")))
    m1.append(a)
    
print("\nthe matrix")
for i in range(r):
    for j in range(c):
        print(m1[i][j],end=" ")
    print()
    


the matrix
1 2 
1 2 


In [8]:
#3. Identify their type using type()



a = 5
print(type(a))

b = 4.0
print(type(b))

c = True
print(type(c))

d = dict()
print(type(d))

e = "hello world"
print(type(e))

f = tuple()
print(type(f))

<class 'int'>
<class 'float'>
<class 'bool'>
<class 'dict'>
<class 'str'>
<class 'tuple'>


In [9]:
'''4. Perform mathematical operations on these 
datasets created - multiplication, division, poweroff'''

import numpy as np

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([2,5,3,8,2])

print("\nAddition")
print(arr1 + arr2)
print("\nMultiply")
print(arr1 * arr2)
print("\nDivide")
print(arr1 / arr2)
print("\nPoweroff")
print(arr1 ** arr2) 



Addition
[ 3  7  6 12  7]

Multiply
[ 2 10  9 32 10]

Divide
[0.5 0.4 1.  0.5 2.5]

Poweroff
[    1    32    27 65536    25]


In [10]:
'''5. Combine text with Numpy fuction to generate a 
textual output - ”Addition of Two: array1 +array 2'''

import numpy as np

arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[4,5,6],[1,2,3]])

print("Addtion of Two : array + array2 \n", arr1+arr2)

Addtion of Two : array + array2 
 [[5 7 9]
 [5 7 9]]


In [11]:
# 6. Implement np.sin(), log(), log2(), np.exp())

import numpy as np

print("sin(90 rad):",np.sin(90))
print("sin(90 deg):",np.sin(np.radians(90)))
print("log(10):",np.log(10))
print("log2(4):",np.log2(4))
print("exp(3):",np.exp(3)) 

sin(90 rad): 0.8939966636005579
sin(90 deg): 1.0
log(10): 2.302585092994046
log2(4): 2.0
exp(3): 20.085536923187668
